Feature/wms image layer
Netherlands3D/twin pull request #196
Opened 2024-07-11 16:59 UTC by bozmir

feature for province of utrecht for sensor data. 
sensordataprojectionlayer is deriving from imageprojectionlayer to keep the initial setup clean.
it also holds a sensordatacontroller component which parses the data into cells. After that a texture is generated based on these cells in the target tile in the tilesensordatacontroller (attached and destroyed with the tile creation process). Cells are cleared afterwards from memory.
The texture generation component has an option to generate a hexgrid or just only the cells in the grid in case of requiring optimization (hexagonalPatternEnabled = true; in tilesensordatacontroller).

2024-07-15 16:56 UTC, bozmir commented
Hoi Mike en Wietse, sam liet me weten dat ik bij jullie moest zijn. Stakeholder Utrecht verwacht oplevering in augustus. Zodat in gebruik kan zijn in september

2024-07-17 06:34 UTC, mvriel commented
@bozmir Ik moet nog in detail door de PR, maar het eerste dat mij opvalt:

- Ik had eigenlijk verwacht / gehoopt dat er een los mapje UrbanRelief zou zijn met daarin alle assets voor de dit onderdeel. Op dit moment is dit namelijk specifiek voor de partij UrbanRelief of PientereTuinen (ik weet even niet wat de meest passende en toegespitste term zou zijn) en geen deel van de core functionaliteit
- Als gevolg daarvan had ik maar 1 Functionality verwacht "Urban Relief / PientereTuinen" verwacht, mocht je een reden hebben waarom elke laag een aparte functionality is, laat het mij even weten.
- Ik zie ook geen optie om de lagen aan of uit te schakelen in het toevoegen paneel (ik denk dat dat het idee was achter de losse functionalities?); het zou top zijn om een mapje PientereTuinen / UrbanRelief te hebben in het toevoegen paneel waar we -vergelijkbaar met de basislagen- de lagen aan en uit kunnen zetten
- Nu zijn de lagen by default aanwezig in het lagenpaneel, maar dit is niet wenselijk voor de Twin zelf. Als gevolg kunnen we dit nu niet mergen naar main, de functie hierboven en de in ontwikkeling zijnde projecten functionaliteit kunnen helpen om een standaard inrichting voor Utrecht te regelen

Ik denk dat wij als team nog moeten nadenken hoe we een mogelijkheid aan kunnen bieden dat het inrichten van dat toevoegen paneel vanuit code of een event geregeld kan worden zodat dit echt een losse package zou kunnen worden

2024-07-17 06:35 UTC, mvriel commented
Ik zie ook nog 4 TODO's en wat uitgecommentarieerde code, wat gaan we daarmee doen?

2024-08-05 08:49 UTC, mvriel commented
@bozmir je wil waarschijnlijk naar https://github.com/Netherlands3D/twin/pull/211 kijken en wat de impact op jouw werk is; het lastige is dat we momenteel bezig zijn met een opslag systeem waarbij sommige zaken dynamischer worden en daarmee het lagensysteem nu een flinke update krijgt

2024-08-28 15:09 UTC, mvriel commented on Assets/Scenes/Main.unity
> +    - target: {fileID: 6178400463341988642, guid: 5fbb7c7c8ec47e849afba1b658f3e07e,
Klopt het dat ik hier een rits aan functionalities zie? Er is er nu toch maar 1 bijgekomen? Of lees ik dit verkeerd?

2024-08-28 15:10 UTC, mvriel commented on Assets/Scenes/Main.unity
> +    - target: {fileID: 7544585871087336863, guid: 5fbb7c7c8ec47e849afba1b658f3e07e,
Ik meen mij te herinneren dat dit testdata was? Of heet deze alleen 'testDecal'?

2024-08-28 15:13 UTC, mvriel commented on Assets/UrbanReleaf/ColorPicker/ColorPicker shader.shader
> +Shader "UI/ColorPicker"
Een handgeschreven shader ipv een in Shadergraph? Jij durft :P

2024-08-28 15:18 UTC, mvriel commented on ProjectSettings/BurstAotSettings_Android.json
> +{
Hoort deze in deze PR?

2024-08-28 15:18 UTC, mvriel commented on ProjectSettings/BurstAotSettings_StandaloneWindows.json
> +    "Version": 4,
Hoort dit in deze PR?

2024-08-28 15:19 UTC, mvriel commented on Assets/Rendering/Twin_UniversalRenderPipelineAsset.asset
> +  m_ShadowDistance: 1950
Horen de changes in deze file in deze PR?

2024-08-28 15:23 UTC, mvriel commented
PR ziet er goed uit, ik heb niet alle code door een fijne kam gehaald op robustheid omdat ik dat overkill vond; ik zag wel wat project files waarvan ik niet kon bedenken waarom deze changed zouden moeten zijn, dus even de vraag gesteld of dat nodig is voor deze PR

2024-08-28 15:24 UTC, mvriel requested changes
Zie hierboven

2024-09-02 07:09 UTC, mvriel approved these changes
I have restored the BurstAotSettings as they are on main; and with that: let's merge it :)

2024-09-02 07:24 UTC, mvriel commented
Merge conflicts; I'll resolve them quickly so that we can merge this and 'er een strik omheen kunnen doen' ;)

2024-09-02 07:41 UTC, merged