Updated Button UI Logic to block items when non interactable
Netherlands3D/twin pull request #256
Opened 2024-09-17 10:00 UTC by Protofunk

2024-09-17 12:20 UTC, mvriel commented on Assets/Scripts/UI/Components/UIButtonLogic.cs
> +            ButtonState(ThisButton.IsInteractable());
Kan je hier een check omheen zetten dat de ButtonState alleen getriggered word als IsInteractable gewijzigd is tov de vorige frame? Dat scheelt performance, en zeker met buttons kan het anders oplopen

2024-09-17 12:21 UTC, mvriel commented on Assets/Scripts/UI/Components/UIButtonLogic.cs
> +            ButtonState(ThisButton.IsInteractable());
Tevens lees ik in de ButtonState methode dat die GetComponent calls doet; die zijn notoir slecht voor de performance, zeker als het in een update gebeurd. Kan je daar ook "ThisButton" gebruiken?

2024-09-17 12:25 UTC, mvriel requested changes
Ik zie hier een potentieel performance probleem, zeker als er meer en meer buttons komen. Dat ben ik graag voor

2024-10-01 07:18 UTC, mvriel commented
Shit, ik had deze eerst moeten reviewen voordat ik het verplaatsen van de Sun Assets mergde.. ik kan de merge conflicts resolven zodra ik weer achter mijn IDE zit

2024-10-03 11:02 UTC, mvriel commented
Merge conflict resolved; ik wacht op de feature branch build

2024-10-04 06:34 UTC, mvriel commented
Er zit iets in deze feature branch wat leidt tot errors gerelateerd aam, wat lijkt, jslib referenties?
![image](https://github.com/user-attachments/assets/b9b01d0c-9e10-429a-b20c-e1f91da6627b)
![image](https://github.com/user-attachments/assets/0201faf3-4f2a-426b-8111-5e73a8c90f27)

Dit moet eerst uitgezocht worden want dat betekent dat de huidige branch niet gemerged kan worden

2024-10-10 09:31 UTC, mvriel approved these changes

2024-10-10 09:32 UTC, mvriel commented
Closed, is door https://github.com/Netherlands3D/twin/pull/284 vervangen

2024-10-10 09:32 UTC, closed without merging

2024-10-10 13:51 UTC, bozmir commented on Assets/Scripts/UI/Components/UIButtonLogic.cs
>              }
dit stuk lijk je 2 keer te gebruiken ook in pointerup, kan je misschien gewoon een method maken zoals,

private void EnableButton()
{
  bool interactable = button.interactable;
  Color color = interactable ? BaseTextColor : DisabledTextColor;
  if (ButtonText != null)
  {
      ButtonText.overrideColorTags = true;
      ButtonText.color = color;
  }
  if (Icon != null)
  {
      Icon.color = color;
  }
}

2024-10-10 13:51 UTC, bozmir commented on Assets/Scripts/UI/Components/UIToggleLogic.cs
> +                }
ook hier even method maken EnableButton() en in start en pointerup uitvoeren

2024-10-10 13:51 UTC, bozmir commented on Assets/_Functionalities/Sun/Scripts/ToggleSpeedButton.cs
> +                button.GetComponent<UIButtonLogic>().Enable_Button();
kan je UIButtonLogic class scope cachen. GetComponent is zwaar