Feature/layer credentials needed UI
Netherlands3D/twin pull request #286
Opened 2024-10-09 14:32 UTC by TomSimons

2024-10-15 14:00 UTC, bozmir requested changes
Heel tof hoe je dit wist om te bouwen tot iets meer losgetrokken structuur.

2024-10-16 12:02 UTC, TomSimons commented on Assets/Scripts/Layers/LayerTypes/Tile3DLayerGameObject.cs
>          private void OnEnable()
scherp

2024-10-16 12:04 UTC, TomSimons commented on Assets/Scripts/Layers/LayerTypes/Tile3DLayerGameObject.cs
> +            {
wow, dat is geen zeurpuntje hoor, ik weet niet wat ik aan het doen was dat ik dit durfde te committen

2024-10-16 12:05 UTC, TomSimons commented on Assets/Scripts/Layers/LayerTypes/ILayerWithCredentials.cs
> +        // public CredentialsInputPropertySection InputPropertySection { get; set; }
ja

2024-10-16 12:07 UTC, TomSimons commented on Assets/Scripts/Layers/LayerUIManager.cs
> +            return disabledLayerTypeSprites[0];
Deze functie wordt niet eens gebruikt, ik haal het weg

2024-10-16 12:17 UTC, TomSimons commented on Assets/Scripts/Layers/Properties/PropertyPanels/CredentialsPropertySectionInstantiator.cs
> +            var settings = Instantiate(inputPropertySectionPrefab, properties);
dit is het property section paneel, dus die wordt weer gedestroyed als het property paneel sluit

2024-10-16 12:19 UTC, TomSimons commented on Assets/Scripts/Layers/Properties/PropertyPanels/LayerCredentialsHandler.cs
> +        //
done

2024-10-16 12:20 UTC, TomSimons commented on Assets/Scripts/Layers/Properties/PropertyPanels/LayerCredentialsHandler.cs
> +            else
done

2024-10-16 12:26 UTC, TomSimons commented on Assets/Scripts/Layers/Properties/PropertyPanels/CredentialsValidationPropertySection.cs
> +                handler = value;
na overleg besloten dit zo te laten

2024-10-16 12:59 UTC, TomSimons commented on Assets/Scripts/Layers/Properties/PropertyPanels/CredentialsPropertySectionInstantiator.cs
> +        [HideInInspector] public UnityEvent<GameObject> OnCredentialsPropertySectionInstantiated = new();
Na overleg heb ik heb dit nu weggehaald, de functie hiervan was dat de key na het heropenen van het credentials paneel alvast pre-ingevuld was. Maar omdat we nu die andere UI hebben is dit een hele niche QOL feature en lijkt het me de moeite niet waard die het zou kosten om dit weer te maken

2024-10-16 13:47 UTC, bozmir approved these changes

2024-10-16 15:14 UTC, TomSimons commented on Assets/Scripts/Layers/Properties/PropertyPanels/CredentialsPropertySectionInstantiator.cs
> +        [HideInInspector] public UnityEvent<GameObject> OnCredentialsPropertySectionInstantiated = new();
Ik heb hiervoor een comment toegevoegd

2024-10-16 15:42 UTC, merged