Feature/geojson bestanden opslaan en inladen
Netherlands3D/twin pull request #289
Opened 2024-10-15 11:40 UTC by bozmir

test
https://cdn-dev-ams-3da.azureedge.net/autobuild/feature/geojson-bestanden-opslaan-en-inladen/1316419187/
jira
https://gemeente-amsterdam.atlassian.net/browse/S3DA-1079

2024-10-15 14:19 UTC, mvriel commented on Assets/Scripts/Layers/Properties/PropertyData/LayerURLPropertyData.cs
> +        [DataMember] private Uri data;
Door de field name te wijzigen breek je backwards-compatibility met eerdere versies van de project bestanden, in die project bestanden heet het veld nu 'url', maar na jouw change 'data'. Voor backwards compatibility zou ik de field url blijven noemen

2024-10-15 14:32 UTC, mvriel requested changes
Backwardscompatibility break in project file - die is zo te zien niet nodig

2024-10-17 14:41 UTC, TomSimons approved these changes
een paar kleine comments maar niks groots, werkt goed!

2024-10-17 14:41 UTC, TomSimons commented on Assets/Scripts/Layers/Adapters/DataTypeAdapters/GeoJSONImportAdapter.cs
> +            var fullPath = localFile.LocalFilePath;
dit is niet de fullPath, maar de local path (Application.PersistentDatapath + fullPath is de absolute path). maar volgens mij heeft dit verder geen invloed op de rest

2024-10-17 14:41 UTC, TomSimons commented on Assets/Scripts/Layers/Adapters/DataTypeAdapters/GeoJSONImportAdapter.cs
> +            if (localFile.SourceUrl.StartsWith("http") || localFile.SourceUrl.StartsWith("https"))
localFile.SourceUrl.StartsWith("https") is overbodig omdat dan ook localFile.SourceUrl.StartsWith("http") true is

2024-10-21 05:56 UTC, mvriel approved these changes

2024-10-21 05:57 UTC, mvriel commented
Ik heb de PR gereviewed en ook getest met een remote en een lokale geojson (tegelijk) en dit werkt 👌

2024-10-21 05:57 UTC, merged