Bugfix/geojson performance
Netherlands3D/twin pull request #331
Opened 2024-11-28 09:01 UTC by TomSimons

increased geojson parsing performance by spreading parsing over multiple frames

2024-11-28 11:48 UTC, bozmir requested changes
zelfde als atm branch

2024-11-28 11:48 UTC, bozmir commented on Assets/Scripts/Layers/LayerTypes/GeoJSONPointLayer.cs
> +                RemoveFeature(kvp);
zelfde als de pr van de atm branch. collection modified exception potentieel

2024-12-02 13:07 UTC, bozmir approved these changes
paar zeur commentjes maar verder prima

2024-12-02 13:53 UTC, TomSimons commented on Assets/Scripts/BatchedMeshInstanceRenderer.cs
> +            RecalculatePointCount();
Ja, maar die heb ik daar dus specifiek uitgehaald

2024-12-02 13:56 UTC, TomSimons commented on Assets/Scripts/BatchedMeshInstanceRenderer.cs
> +            int currentBatchSize = 1023;
ik laat dit nu zo, bij de volgende optimalisatie ronde kan dit eventueel meegenomen worden

2024-12-02 13:56 UTC, merged