Feature/snackbar
Netherlands3D/twin pull request #47
Opened 2023-12-11 13:43 UTC by TomSimons

Added snackbar and csv overwrite message.
Snackbar is available through a string event and will automatically pop up when a message is sent here.

2023-12-11 16:05 UTC, sambaas requested changes
yo tom; ik denk dat overal waar we voor nu het SO event system willen gebruiken we beter de UnityEvent <datatype> events kunnen gebruiken. Dan is evengoed het SO event systeem te gebruiken, maar is er geen afhankelijkheid in de code.

2023-12-11 16:05 UTC, sambaas commented on Assets/Scripts/Layers/Adapters/CSVImportAdapter.cs
> +        [SerializeField] private StringEvent csvOverwriteMessageEvent;
Ik denk dat het wijs is om ipv. ons EventSystem te gebruiken als dependency hier UnityEvent< string > te gebruiken. Je kan dan alsnog die SO's gebruiken, maar hebben we geen dependencies in de scripts meer zitten

2023-12-11 16:25 UTC, TomSimons commented on Assets/Scripts/UI/Snackbar.cs
> +        public StringEvent snackbarMessageEvent;
true, zal ik aanpassen

2023-12-11 16:31 UTC, TomSimons commented on Assets/Scripts/UI/Snackbar.cs
> +        public StringEvent snackbarMessageEvent;
Hm, ik was te snel, het idee hiervan is dat er 1 event asset waar je een string in kan gooien die dan een snackbar message opent, dat werkt niet met een UnityEvent, heb je een idee hoe we dit zouden kunnen oplossen?

2023-12-12 09:25 UTC, sambaas approved these changes
nijs; alleen die Netherlands3D.Events using kan nu weg

2023-12-12 09:25 UTC, sambaas commented on Assets/Scripts/Layers/Adapters/CSVImportAdapter.cs
> +using Netherlands3D.Events;
deze kan nu weg

2023-12-12 09:26 UTC, merged