Feature/enable disable functions
Netherlands3D/twin pull request #72
Opened 2024-01-31 14:53 UTC by sambaas

- Renamed 'Feature' to 'Functionality' in scripts and assets to match UI design terminology
- Changed settings functionalities Panel to match UI design
- Added new event to SetupWizard to report changed settings
- Trigger snackbar with message stating the settings were changed
- Force a min and max width for the settings panel ( to avoid extremes on thin or wider screens )
- Added Title next to Caption for Functionality data object
- Seperated clicking text and checkbox of functionalities to prepare for upcoming Functionality explanations

2024-01-31 15:32 UTC, mvriel commented on Assets/Scripts/UI/MinMaxWidth.cs
> +    [ExecuteInEditMode]
Moet deze echt ExecuteInEditMode zijn? Want dat kan serialized changes betekenen en onverwachte changes in de Scene files. Als di bedoelt is voor OnValidate, dat zou niet moeten hoeven omdat OnValidate juist alleen in Edit mode gebeurd

2024-02-01 09:18 UTC, TomSimons requested changes

2024-02-01 09:18 UTC, TomSimons commented on Assets/Scripts/Configuration/SetupWizard.cs
[SerializeField] private GameObject featureList;

        [Header("Prefab")] [SerializeField] private Toggle featureSelectionPrefab;
        [Header("Prefab")] [SerializeField] private FunctionalitySelection featureSelectionPrefab;
        

        moeten deze niet ook gerenamed worden naar functionality?

2024-02-01 09:18 UTC, TomSimons commented on Assets/Scripts/Configuration/SetupWizard.cs
Is die Debug.Log nog nodig?

2024-02-01 09:18 UTC, TomSimons commented on Packages/eu.netherlands3d.twin-functionalities/Scripts/EnableComponentsByFunctionality.cs
waarom try finally hier?

2024-02-01 09:18 UTC, TomSimons commented on Packages/eu.netherlands3d.twin-functionalities/Scripts/EnableComponentsByFunctionality.cs
Kan de OnValidate in een #if Unity_Editor blok?

2024-02-01 09:41 UTC, TomSimons commented
Nog iets dat ik na testen tegenkwam: als je het obj importvinkje uitzet kan je alsnog wel objs importeren via het layer panel

2024-02-01 11:11 UTC, mvriel commented on Packages/eu.netherlands3d.twin-functionalities/Scripts/EnableComponentsByFunctionality.cs
Is dat nodig? OnValidate is editor-only: https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnValidate.html

2024-02-01 11:23 UTC, mvriel commented
> Nog iets dat ik na testen tegenkwam: als je het obj importvinkje uitzet kan je alsnog wel objs importeren via het layer panel

Dit "klopt"; we hadden tijdens de reviews geconstateerd dat de interactie tussen het instellingenscherm en het lagenpaneel nog niet helemaal werkt zoals we willen; maar wat we willen was ook onduidelijk. Daarom hebben we issue 630 om te inventariseren wat het exacte effect van een functie is, en in de volgende sprint zit een issue om de samenwerking tussen het lagenpaneel en de instellingen recht te trekken in 518. Hoewel ik zie dat de acceptatiecriteria van 518 dit wel _iets_ duidelijker mag duidden

2024-02-01 13:08 UTC, TomSimons commented on Packages/eu.netherlands3d.twin-functionalities/Scripts/EnableComponentsByFunctionality.cs
maar de code wordt volgens mij niet automatisch gestript, of dat is in een nieuwere versie van unity veranderd

2024-02-01 13:10 UTC, mvriel commented
in overleg met Tom, omdat deze PR nogal wat raakt en de overgebleven comments geen functionele impact op de applicatie lijken te hebben verplaats ik de opmerkingen naar de Jira issue en merge ik deze alvast

2024-02-01 13:10 UTC, merged

2024-02-01 13:13 UTC, mvriel commented on Packages/eu.netherlands3d.twin-functionalities/Scripts/EnableComponentsByFunctionality.cs
Hmm, dat weet ik niet. Ikzelf maak mij er niet heel erg druk om omdat een paar regels code hier het verschil niet gaan maken in de build size vanwege compression; maar ik verplaats ook deze vraag even naar de Jira issue zodat Sam ook zijn input kan geven. Wellicht dat ik het compleet mis heb en dan is dat voor mij een mooi leermoment :D

2024-02-05 13:38 UTC, sambaas commented on Packages/eu.netherlands3d.twin-functionalities/Scripts/EnableComponentsByFunctionality.cs
Ik zet m' wel in een #if UNITY_EDITOR blok; hij stripped die methods anders niet 🤔👍

2024-02-05 14:05 UTC, sambaas commented on Packages/eu.netherlands3d.twin-functionalities/Scripts/EnableComponentsByFunctionality.cs
stukje legacy; heb mike al laten weten dat try/catches niet handig zijn voor als we later exception handling op None willen zetten (enorme performance boost voor WebGL)
heb m voor nu weggehaald; er werd toch niets gecatched